### ISSUE TITLE
GLN should not be required for practitioner

### ISSUE THREAD

**Issue by msmock** [hl7ch/ch-vacd#154]
While implementing the vaccination module for the EPR we run into trouble with the requirement that the GLN must be set as identifier for practitioner resources for the performer role. The GLN used as identifier in the EPD is only known if the vaccination is entered by the practitioner or an assistant, i.e., when the performer is the author of the vaccination entry. 

In all other cases the GLN is not known in general, e.g., when the patient enters the vaccination data or if old vaccination records are migrated. In these cases we currently are forced to use a workaround and set the GLN to an arbitrary value (the GLN of eHealth Suisse) to fulfill the requirement defined in the IG. 

The MUST requirement for the GLN identifier in the practitioner resource defined in the IG shall be weakened to a SHOULD or MUST IF KNOWN.

**Comment by ralych** [comment]
The GLN  is mandatory by the EPR profile from the ch-core.
To change this, we have to change all resources to not pointing to the EPR profiles.
in my opinion not correct to switch to generic ch-core profiles as of the the documents are sed in EPR context.

to be discussed in the WG.

**Comment by oliveregger** [comment]
having the performer required as a gln is not something done in CH-EMED profile resources Medication* (there it is the informationSource but not requiring a GLN from the Practitioner) e.g: http://build.fhir.org/ig/hl7ch/ch-emed/StructureDefinition-ch-emed-composition-medicationcard.html since we wan't to reuse those profiles in non EPR Usecases, I don't think a reference from to an EPR Profile should be made.

however it is required for the author of the document (see http://build.fhir.org/ig/hl7ch/ch-emed/StructureDefinition-ch-emed-composition-medicationcard.html)

**Comment by msmock** [comment]
yes, the GLN is mandatory for the author of the document. Since we don't get it from the portal when starting the vaccination module, we don't know the GLN when producing the VaccinationAdminstration document. There are other vaccination use cases as well, where we might not know the GLN, e.g., documents authored by HP which use a Zusatzdienst to create the document in en external system and upload it via their archive system. We wonder if a mandatory GLN is realistic and useful.

**Comment by ralych** [comment]
The GLN is the identificator for a HCP. Thus setting this mandatory should not be any problem in using it.
In digital data exchange nothing else than unique identifiers is mandatory to reduce conflicts and wrong informations.
The exchange formats i.e. ch-vacd should not solve the problems of implementation lacks of applications.
