### ISSUE TITLE
Feedback KSW (Kantonsspital Winterrhur) (Daniel Ratschiller, CISTEC AG)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#195]
ch.fhir.ig.ch-vacd#4.0.0-ballot /

One of our clients, KSW, does not want to use the vaccination tool productively because they have noticed deficiencies in the CH VACD mapping disease vaccinations:
- There is a Comirnaty preparation that is not mapped to COVID.
- There is Gardasil 9 and Gardasil, where only Gardasil 9 is mapped to HPV and Gardasil is not.

Daniel Ratschiller, CISTEC AG

**Comment by ralych** [comment]
This is in both cases not correct, see 
http://fhir.ch/ig/ch-vacd/ConceptMap-ch-vacd-vaccines-targetdiseases-cm.html
ans search for Comirnaty or Gardasil

**Comment by drats-cis** [comment]
Hello Roeland

a bit surprised about this wont-do answer, we took a closer look where the different estimation comes from and found this:

There is indeed an inconsistency between two value sets, which needs to be fixed for the practicality of CH-VACD:

Gardasil vaccine-first:
http://fhir.ch/ig/ch-vacd/ConceptMap-ch-vacd-targetdiseases-vaccines-cm.html 
-> correct, there are 2 products: Gardasil 9 +Gardasil
Gardasil disease-first:
http://fhir.ch/ig/ch-vacd/ConceptMap-ch-vacd-vaccines-targetdiseases-cm.html
-> nok, here is only 1 product: Gardasil 9 !

Comirnaty vaccine-first:
http://fhir.ch/ig/ch-vacd/ConceptMap-ch-vacd-targetdiseases-vaccines-cm.html 
-> here are 5 prorducts:
68225 Comirnaty (COVID-19 Vaccine, Pfizer)
68710-01 Comirnaty® 30 micrograms/do
68710-02 Comirnaty® 10 microgram/dose
69047 Comirnaty® Original/Omicron BA.1 15/15 µg per dose
69127 Comirnaty Original/Omicron BA. 4-5 0.225 mg)

Comirnaty disease-first:
http://fhir.ch/ig/ch-vacd/ConceptMap-ch-vacd-vaccines-targetdiseases-cm.html
-> here are only 3 products:
68225 Comirnaty (COVID-19 Vaccine, Pfizer)
68267 Spikevax (COVID-19 Vaccine, Moderna)
68710-02 Comirnaty® 10 micrograms/dose).

And it shows us an important conceptual problem that we have in a primary system, in order to be able to document vaccinations in a primarily disease-oriented and not vaccine product-oriented way, the disease-first value set is even more significant for us and should at least not contradict the first one. 

In this respect, the input from KSW is absolutely correct and the doubts about the degree of maturity are not entirely unjustified. 

Kind regards, 
Daniel, CISTEC AG

**Comment by ralych** [comment]
Thanks to the detailed description, now its more cleare and i will check it. wontfix was mistakenly added but directly removed as you can see in the log....

To the last comment i will not answer. we will have a meeting to clarify.

The current build of the fixes can be found here:
http://build.fhir.org/ig/hl7ch/ch-vacd/branches/ballot_resolution_400/terminology.html

**Comment by pjolo** [comment]
good
